// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kggflbsusrbfqkvlgpxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnZ2ZsYnN1c3JiZnFrdmxncHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjU5ODksImV4cCI6MjA2MDMwMTk4OX0.1Hn7mZQRDWuGw77J31oYjzIpDZ4KooCZEi9uAXzNJEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);